//auth
export const LOGOUT = 'LOGOUT';

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_USER_REQUEST_ERROR = 'LOGIN_USER_REQUEST_ERROR';

export const CONFIRM_USER_EMAIL_REQUEST = 'CONFIRM_USER_EMAIL_REQUEST';
export const CONFIRM_USER_EMAIL_SUCCESS = 'CONFIRM_USER_EMAIL_SUCCESS';
export const CONFIRM_USER_EMAIL_ERROR = 'CONFIRM_USER_EMAIL_ERROR';

export const SIGN_UP_USER_REQUEST = 'SIGN_UP_USER_REQUEST';
export const SIGN_UP_USER_SUCCESS = 'SIGN_UP_USER_SUCCESS';
export const SIGN_UP_USER_ERROR = 'SIGN_UP_USER_ERROR';

export const AUTHORIZE_USER_REQUEST = 'AUTHORIZE_USER_REQUEST';
export const AUTHORIZE_USER_SUCCESS = 'AUTHORIZE_USER_SUCCESS';
export const NOT_AUTHORIZED_USER = 'NOT_AUTHORIZED_USER';

export const PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_ERROR = 'PASSWORD_RESET_ERROR';

export const PASSWORD_RESET_EMAIL_REQUEST = 'PASSWORD_RESET_EMAIL_REQUEST';
export const PASSWORD_RESET_EMAIL_SENT = 'PASSWORD_RESET_EMAIL_SENT';
export const PASSWORD_RESET_EMAIL_ERROR = 'PASSWORD_RESET_EMAIL_ERROR';

export const TOKEN_VERIFY_REQUEST = 'TOKEN_VERIFY_REQUEST';
export const TOKEN_VERIFY_SUCCESS = 'TOKEN_VERIFY_SUCCESS';
export const TOKEN_VERIFY_ERROR = 'TOKEN_VERIFY_ERROR';

// user account
export const USER_SAVE_ACCOUNT_REQUEST = 'USER_SAVE_ACCOUNT_REQUEST';
export const USER_SAVE_ACCOUNT_SUCCESS = 'USER_SAVE_ACCOUNT_SUCCESS';
export const USER_SAVE_ACCOUNT_ERROR = 'USER_SAVE_ACCOUNT_ERROR';

//langauge
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const CHANGE_LANGUAGE_ERROR = 'CHANGE_LANGUAGE_ERROR';
